title: Shaomin Liang's Homepage
page-top-title: Shaomin Liang
top-section-bg-text: Applied mechanics
home-subtitle: Shaomin Liang&ensp;|&ensp;梁绍敏
copyright-text: '&copy; Shaomin Liang 2021-2026. All Rights Reserved.'
