title: Shaomin Liang's Homepage
page-top-title: Shaomin Liang
top-section-bg-text: Mechanics of Materials
home-subtitle: Shaomin Liang&ensp;|&ensp;梁绍敏
copyright-text: '&copy; Shaomin Liang 2016-2026. All Rights Reserved.'
